package com.example.longrunner.game.core

import com.example.longrunner.game.player.CharacterData

enum class GameState {
    READY,
    RUNNING,
    PAUSED,
    GAME_OVER
}

/**
 * Snapshot of current gameplay and character progression metrics for UI observation.
 */
data class GameStats(
    val score: Long = 0,
    val distance: Float = 0f,
    val shards: Int = 0,
    val credits: Int = 0,
    val combo: Int = 1,
    val comboProgress: Float = 0f,
    val nearMisses: Int = 0,
    val multiplier: Int = 1,
    val isBoostActive: Boolean = false,
    val isNearMissActive: Boolean = false,
    val speed: Float = GameConstants.BASE_SPEED,
    val highScore: Long = 0,
    val state: GameState = GameState.READY,
    val character: CharacterData = CharacterData.KAI,
    val isAbilityReady: Boolean = true,
    val isAbilityActive: Boolean = false,
    val abilityCooldownProgress: Float = 0f,
    val abilityName: String = "Quick Phase",
    val bankCredits: Int = 0,
    val phaseEnergyProgress: Float = 0.5f,
    val isPhaseShiftActive: Boolean = false,
    val canActivatePhaseShift: Boolean = true,
    val isFractureWarning: Boolean = false,
    val fractureWarningTitle: String = "",
    val fractureWarningSubtitle: String = "",
    val isInFractureZone: Boolean = false,
    val activeRouteName: String = "",
    val fractureClearMessage: String = "",
    val hasShield: Boolean = false,
    val shieldProgress: Float = 0f,
    val isOverdriveActive: Boolean = false,
    val overdriveProgress: Float = 0f,
    val isPhaseBatteryActive: Boolean = false,
    val phaseBatteryProgress: Float = 0f,
    val isTimeBrakeActive: Boolean = false,
    val timeBrakeProgress: Float = 0f,
    val isScoreAmplifierActive: Boolean = false,
    val scoreAmplifierProgress: Float = 0f,
    val isMagnetActive: Boolean = false,
    val magnetProgress: Float = 0f,
    val isHoverboardActive: Boolean = false,
    val hoverboardProgress: Float = 0f,
    val hoverboardCharges: Int = 1,
    val equippedHoverboard: com.example.longrunner.game.powerups.HoverboardData = com.example.longrunner.game.powerups.HoverboardData.VECTOR_GLIDE,
    val worldEventType: com.example.longrunner.game.world.WorldEventType = com.example.longrunner.game.world.WorldEventType.NONE,
    val isWorldEventWarning: Boolean = false,
    val worldEventTitle: String = "",
    val worldEventSubtitle: String = "",
    val worldEventProgress: Float = 0f,
    val nullDistance: Float = 18.0f,
    val nullTension: Float = 0f,
    val isNullAlert: Boolean = false,
    val isNullCritical: Boolean = false,
    val operativeRank: Int = 1,
    val rankTitle: String = "CYBER CADET",
    val rankProgress: Float = 0f,
    val currentRankXp: Int = 0,
    val xpToNextRank: Int = 500,
    val totalXp: Long = 0L,
    val activeMissions: List<com.example.longrunner.game.progression.Mission> = emptyList(),
    val totalMissionsCompleted: Int = 0,
    val missionBannerMessage: String = "",
    val achievementsUnlockedCount: Int = 0,
    val totalAchievementsCount: Int = 10,
    val achievementBannerMessage: String = "",
    val unclaimedMissionsCount: Int = 0,
    val fps: Int = 60,
    val frameTimeMs: Float = 16.6f
)
